#!/bin/bash

printf "Welcome. How many messages do you wish to receive?\n"
read message_amount
if [[ "$message_amount" =~ ^[1-9][0-9]?$|^100$ ]]; then
	for (( c=0; c<"$message_amount"; c++ ))
		do
			curl -i -H "Content-Type: application/json" -X POST http://localhost:5000/api/queue/pop
		done
else
	printf "You have to specify a natural number up to 100.\n"
fi

